# Clean stale build artifacts for lib60870-C
# Removes files/directories that frequently cause issues when left over from older builds
# Safe by default and supports a Dry-Run and Deep clean mode.

param(
    [switch]$DeepClean,   # Also purge vendor build leftovers (e.g., mbedTLS in-tree builds)
    [switch]$DryRun       # Show what would be removed without actually deleting
)

$ErrorActionPreference = 'Stop'
$rootDir = $PSScriptRoot
Set-Location $rootDir

function Remove-ItemsSafely {
    param(
        [Parameter(Mandatory=$true)] [System.Collections.IEnumerable] $Items,
        [switch]$AsDirectories,
        [string]$Label = "items"
    )

    $total = 0
    foreach ($i in $Items) {
        if ($AsDirectories) {
            if (Test-Path $i -PathType Container) {
                Write-Host ("  - Removing dir: {0}" -f $i) -ForegroundColor Yellow
                Remove-Item $i -Recurse -Force -ErrorAction SilentlyContinue -WhatIf:$DryRun
                $total++
            }
        } else {
            if (Test-Path $i) {
                Write-Host ("  - Removing: {0}" -f $i) -ForegroundColor Yellow
                Remove-Item $i -Recurse -Force -ErrorAction SilentlyContinue -WhatIf:$DryRun
                $total++
            }
        }
    }
    if ($total -gt 0) {
        Write-Host ("    [OK] Removed {0} {1}" -f $total, $Label) -ForegroundColor Green
    } else {
        Write-Host ("    [OK] No {0} found" -f $Label) -ForegroundColor DarkGray
    }
}

function Remove-ByNameRecursively {
    param(
        [Parameter(Mandatory=$true)] [string] $Name,
        [string[]] $Under = @('.')
    )
    foreach ($base in $Under) {
        if (Test-Path $base) {
            $foundDirs = Get-ChildItem -Path $base -Recurse -Directory -Filter $Name -ErrorAction SilentlyContinue
            foreach ($m in $foundDirs) {
                Write-Host ("  - Removing dir: {0}" -f $m.FullName) -ForegroundColor Yellow
                Remove-Item $m.FullName -Recurse -Force -ErrorAction SilentlyContinue -WhatIf:$DryRun
            }
        }
    }
}

function Remove-FilesRecursively {
    param(
        [string[]] $Includes,
        [string[]] $Under = @('.')
    )
    foreach ($base in $Under) {
        if (Test-Path $base) {
            $files = Get-ChildItem -Path $base -Recurse -File -Include $Includes -ErrorAction SilentlyContinue
            foreach ($f in $files) {
                Write-Host ("  - Removing file: {0}" -f $f.FullName) -ForegroundColor Yellow
                Remove-Item $f.FullName -Force -ErrorAction SilentlyContinue -WhatIf:$DryRun
            }
        }
    }
}

Write-Host "========================================" -ForegroundColor Cyan
Write-Host "  Cleaning stale build artifacts (lib60870-C)" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host "Root: $rootDir" -ForegroundColor Gray
if ($DryRun) { Write-Host "Mode: DRY-RUN (no files will be deleted)" -ForegroundColor Yellow }
if ($DeepClean) { Write-Host "Mode: DEEP CLEAN (vendor leftovers included)" -ForegroundColor Yellow }
Write-Host ""

# 1) Root-level build folders commonly created by CMake/VS
$rootDirs = @(
    "build",
    "build-*",
    ".vs",
    "out",
    "x64",
    "Debug",
    "Release"
) | ForEach-Object { Join-Path $rootDir $_ }

Write-Host "[1/7] Removing root-level build folders..." -ForegroundColor Yellow
Remove-ItemsSafely -Items $rootDirs -AsDirectories -Label "root build folders"

# 2) CMake cache and scaffolding anywhere in the tree
Write-Host "[2/7] Removing CMake cache and scaffolding..." -ForegroundColor Yellow
Remove-FilesRecursively -Includes @("CMakeCache.txt", "cmake_install.cmake", "install_manifest.txt", "Makefile", "compile_commands.json") -Under @(".")
Remove-ByNameRecursively -Name "CMakeFiles" -Under @(".")

# 3) Visual Studio project/solution files generated by CMake
Write-Host "[3/7] Removing generated VS project files..." -ForegroundColor Yellow
Remove-FilesRecursively -Includes @("*.sln", "*.vcxproj", "*.vcxproj.filters", "*.vcxproj.user") -Under @(".")

# 4) Common MSVC intermediate/object outputs (safe to purge)
Write-Host "[4/7] Removing MSVC intermediates..." -ForegroundColor Yellow
$msvcPatterns = @("*.obj","*.iobj","*.pdb","*.ipdb","*.idb","*.ilk","*.exp","*.tlog","*.lastbuildstate","*.pch","*.log")
Remove-FilesRecursively -Includes $msvcPatterns -Under @(".")

# 5) Known Debug/Release subfolders under build/ and examples/
Write-Host "[5/7] Removing Debug/Release subfolders under build/ and examples/..." -ForegroundColor Yellow
if (Test-Path (Join-Path $rootDir "build")) {
    Remove-ByNameRecursively -Name "Debug" -Under @("build")
    Remove-ByNameRecursively -Name "Release" -Under @("build")
}
if (Test-Path (Join-Path $rootDir "examples")) {
    Remove-ByNameRecursively -Name "Debug" -Under @("examples")
    Remove-ByNameRecursively -Name "Release" -Under @("examples")
}

# 6) Cleaning up .dir directories 
Write-Host "[6/7] Removing .dir directories..." -ForegroundColor Yellow
Remove-ByNameRecursively -Name ".dir" -Under @(".")


# 7) Optional deep-clean: vendor (mbedtls) leftover in-tree builds
if ($DeepClean) {
    Write-Host "[7/7] Deep clean vendor (mbedtls) in-tree build leftovers..." -ForegroundColor Yellow
    $mbedtlsLibDebug = Get-ChildItem -Path (Join-Path $rootDir "dependencies\mbedtls-*\library") -Directory -Filter "Debug" -ErrorAction SilentlyContinue
    $mbedtlsLibRelease = Get-ChildItem -Path (Join-Path $rootDir "dependencies\mbedtls-*\library") -Directory -Filter "Release" -ErrorAction SilentlyContinue
    foreach ($d in @($mbedtlsLibDebug + $mbedtlsLibRelease)) {
        if ($null -ne $d) {
            Write-Host ("  - Removing dir: {0}" -f $d.FullName) -ForegroundColor Yellow
            Remove-Item $d.FullName -Recurse -Force -ErrorAction SilentlyContinue -WhatIf:$DryRun
        }
    }
    # Also remove any CMake scaffolding under dependencies/mbedtls-*
    $mbedtlsRoots = Get-ChildItem -Path (Join-Path $rootDir "dependencies") -Directory -Filter "mbedtls-*" -ErrorAction SilentlyContinue
    foreach ($r in $mbedtlsRoots) {
        Remove-ByNameRecursively -Name "CMakeFiles" -Under @($r.FullName)
        Remove-FilesRecursively -Includes @("CMakeCache.txt", "cmake_install.cmake", "install_manifest.txt", "Makefile", "compile_commands.json") -Under @($r.FullName)
    }
}

Write-Host ""; Write-Host "Cleanup complete." -ForegroundColor Green
if ($DryRun) { Write-Host "(Dry-run: no files were deleted)" -ForegroundColor Gray }
